services:
  axion-ui:
    build: ./axion-ui
    ports:
      - "8080:80"
    networks:
      - axion-network
    depends_on:
      - axion-telemetry-query-service

  axion-ingestion-service:
    build: ./axion-ingestion-service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - axion-network

  axion-telemetry-query-service:
    build: ./axion-telemetry-query-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=8000
    networks:
      - axion-network

  axion-data-simulator:
    build: ./axion-data-simulator
    environment:
      - API_URL=http://axion-ingestion-service:8000/api/v1/telemetry/ingest
      - INTERVAL_SECONDS=5
    networks:
      - axion-network
    depends_on:
      - axion-ingestion-service

networks:
  axion-network:
    driver: bridge
