apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-telemetry-query-service
  namespace: axion-minikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axion-telemetry-query-service
  template:
    metadata:
      labels:
        app: axion-telemetry-query-service
    spec:
      containers:
      - name: axion-telemetry-query-service
        image: axion-telemetry-query-service:minikube
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: axion-postgres-secret
              key: DATABASE_URL
        livenessProbe:
          httpGet:
            path: /devices
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /devices
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: axion-telemetry-query-service
  namespace: axion-minikube
spec:
  selector:
    app: axion-telemetry-query-service
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort
