apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- postgres-external.yaml
- ingestion/deployment.yaml
- telemetry-query/deployment.yaml
- data-simulator/deployment.yaml
- ui/deployment.yaml
