apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- postgres/pvc.yaml
- postgres/service.yaml
- postgres/statefulset.yaml
- postgres/migration-job.yaml
- ingestion/deployment.yaml
- telemetry-query/deployment.yaml
- data-simulator/deployment.yaml
- ui/deployment.yaml
