apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: axion-minikube
spec:
  ports:
  - port: 5432
    targetPort: 5432
  # This Service maps to the Windows host PostgreSQL
  type: ExternalName
  externalName: host.minikube.internal
